on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            var fs = require('fs');
            try {
              fs.mkdirSync('./.github/conditional/tmp', {recursive: true});
            } catch {
            }
            fs.writeFileSync('./.github/conditional/tmp/action.yml', 'name: ciao');
      - run: "pwd"
      - run: "ls"
      - run: "echo $GITHUB_WORKSPACE"
      - run: "echo $HOME"
      - run: "ls .github/conditional/tmp"
      - run: "cat .github/conditional/tmp/action.yml"
      - uses: ./.github/conditional/tmp